import {
  DownloadRounded,
  FileDownloadRounded,
  TableChartRounded,
} from '@mui/icons-material'
import {
  Box,
  Button,
  Card,
  CardContent,
  Chip,
  FormControl,
  Grid,
  InputLabel,
  MenuItem,
  Paper,
  Select,
  Stack,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Typography,
  Skeleton
} from '@mui/material'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import { fetchReports } from '../../store/slices/reportSlice'

const ReportsPage = () => {
  const dispatch = useDispatch()
  const { reports, status } = useSelector((state) => state.report)
  const loading = status === 'loading' || status === 'idle'

  const [reportType, setReportType] = useState('All')
  const [dateRange, setDateRange] = useState('30d')

  useEffect(() => {
    if (status === 'idle') {
      dispatch(fetchReports())
    }
  }, [status, dispatch])

  const filteredRows = useMemo(() => {
    if (!reports) return []
    return reports.filter((row) => {
      const matchesType = reportType === 'All' || row.type === reportType
      return matchesType
    })
  }, [reports, reportType])

  const exportCsv = useCallback((filename = `enterprise-reports.csv`) => {
    if (!filteredRows.length) return
    const csv = [Object.keys(filteredRows[0] || {}).join(','), ...filteredRows.map((row) => Object.values(row).map(v => typeof v === 'object' ? JSON.stringify(v).replace(/,/g, ';') : v).join(','))].join('\n')
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = filename
    link.click()
    URL.revokeObjectURL(url)
  }, [filteredRows])

  const exportExcel = useCallback(() => {
    exportCsv(`enterprise-reports.xlsx`)
  }, [exportCsv])

  return (
    <Box sx={{ display: 'flex', flexDirection: 'column', gap: 3 }}>
      <Box>
        <Typography variant="h4" fontWeight={700} gutterBottom>
          Reporting Center
        </Typography>
        <Typography color="text.secondary">
          Build report views, export sanitized snapshots, and revisit saved reports.
        </Typography>
      </Box>

      <Card>
        <CardContent>
          <Grid container spacing={2}>
            <Grid item xs={12} md={6}>
              <FormControl fullWidth size="small">
                <InputLabel>Report Type</InputLabel>
                <Select value={reportType} label="Report Type" onChange={(event) => setReportType(event.target.value)}>
                  <MenuItem value="All">All Categories</MenuItem>
                  <MenuItem value="Procurement">Procurement</MenuItem>
                  <MenuItem value="Vendor">Vendor</MenuItem>
                  <MenuItem value="Risk">Risk</MenuItem>
                  <MenuItem value="Compliance">Compliance</MenuItem>
                  <MenuItem value="Finance">Finance</MenuItem>
                  <MenuItem value="Operations">Operations</MenuItem>
                  <MenuItem value="Audit">Audit</MenuItem>
                </Select>
              </FormControl>
            </Grid>
            <Grid item xs={12} md={6}>
              <FormControl fullWidth size="small">
                <InputLabel>Date Range</InputLabel>
                <Select value={dateRange} label="Date Range" onChange={(event) => setDateRange(event.target.value)}>
                  <MenuItem value="30d">Last 30 days</MenuItem>
                  <MenuItem value="90d">Last 90 days</MenuItem>
                  <MenuItem value="all">All time</MenuItem>
                </Select>
              </FormControl>
            </Grid>
          </Grid>
        </CardContent>
      </Card>

      <Card>
        <CardContent>
          <Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" spacing={2}>
            <Stack direction="row" spacing={1} alignItems="center">
              <TableChartRounded color="primary" />
              <Typography variant="h6" fontWeight={700}>Available Reports</Typography>
            </Stack>
            <Stack direction={{ xs: 'column', sm: 'row' }} spacing={1}>
              <Button variant="outlined" startIcon={<DownloadRounded />} onClick={() => exportCsv()}>CSV</Button>
              <Button variant="contained" startIcon={<FileDownloadRounded />} onClick={exportExcel}>Excel</Button>
            </Stack>
          </Stack>

          <TableContainer component={Paper} variant="outlined" sx={{ mt: 2 }}>
            <Table size="small">
              <TableHead>
                <TableRow>
                  <TableCell>ID</TableCell>
                  <TableCell>Report Name</TableCell>
                  <TableCell>Category</TableCell>
                  <TableCell>Date Generated</TableCell>
                  <TableCell>Generated By</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {loading ? (
                  Array.from({ length: 5 }).map((_, index) => (
                    <TableRow key={`row-skeleton-${index}`}>
                      <TableCell colSpan={5}><Skeleton variant="text" width="100%" /></TableCell>
                    </TableRow>
                  ))
                ) : filteredRows.length === 0 ? (
                   <TableRow>
                     <TableCell colSpan={5} align="center"><Typography color="text.secondary" sx={{ py: 2 }}>No reports match the criteria.</Typography></TableCell>
                   </TableRow>
                ) : (
                  filteredRows.map((row) => (
                    <TableRow key={row.id} hover>
                      <TableCell>{row.id}</TableCell>
                      <TableCell>{row.name}</TableCell>
                      <TableCell><Chip label={row.type} size="small" variant="outlined" /></TableCell>
                      <TableCell>{row.createdDate}</TableCell>
                      <TableCell>{row.createdBy}</TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </TableContainer>
        </CardContent>
      </Card>
    </Box>
  )
}

export default ReportsPage
